version: '2'
services:
  utdbsample2-app:
    image: utdbsample2
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://utdbsample2-postgresql:5432/utdbSample2
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  utdbsample2-postgresql:
    extends:
      file: postgresql.yml
      service: utdbsample2-postgresql
